"""
Dad Joke Machine — Click for a fresh dose of cringe.
Add your own dad jokes to the JOKES list below.
"""

import tkinter as tk
import random
import math

# ── Add your own dad jokes here ──────────────────────────────────────────
JOKES = [
    "I'm afraid for the calendar.\nIts days are numbered.",
    "What do you call a fish with no eyes?\nFsh.",
    "I only know 25 letters of the alphabet.\nI don't know y.",
    "Why don't skeletons fight each other?\nThey don't have the guts.",
    "What do you call a fake noodle?\nAn impasta.",
    "I told my wife she was drawing her eyebrows too high.\nShe looked surprised.",
    "Why did the scarecrow win an award?\nBecause he was outstanding in his field.",
    "My wife said I should do lunges to stay in shape.\nThat would be a big step forward.",
    "I asked my dog what's 2 minus 2.\nHe said nothing.",
    "What do you call a bear with no teeth?\nA gummy bear.",
    "I used to play piano by ear,\nbut now I use my hands.",
    "Why can't you give Elsa a balloon?\nBecause she will let it go.",
    "How do you make a tissue dance?\nPut a little boogie in it.",
    "I'm reading a book on anti-gravity.\nIt's impossible to put down.",
    "What does a nosy pepper do?\nGets jalapeno business.",
    "What do you call cheese that isn't yours?\nNacho cheese.",
    "Why did the math book look so sad?\nIt had too many problems.",
    "What did the ocean say to the beach?\nNothing, it just waved.",
    "I don't trust stairs.\nThey're always up to something.",
    "Why did the golfer bring two pairs of pants?\nIn case he got a hole in one.",
    "What do you call a pig that does karate?\nA pork chop.",
    "Why don't eggs tell jokes?\nThey'd crack each other up.",
    "I told my computer I needed a break.\nNow it won't stop sending me Kit-Kat ads.",
    "What time did the man go to the dentist?\nTooth-hurty.",
    "How do you catch a squirrel?\nClimb a tree and act like a nut.",
    "Why did the bicycle fall over?\nIt was two-tired.",
    "What do you call a cow with no legs?\nGround beef.",
    "I'm on a whiskey diet.\nI've lost three days already.",
    "What do you call a factory that sells passable products?\nA satisfactory.",
    "Why did the old man fall down the well?\nHe couldn't see that well.",
    "What do you call a man with a rubber toe?\nRoberto.",
    "Why do dads tell such bad jokes?\nThey're just trying to make you groan up.",
    "What's brown and sticky?\nA stick.",
    "Why did the cookie go to the hospital?\nBecause it felt crummy.",
    "What do you call a sleeping bull?\nA bulldozer.",
    "How do you organize a space party?\nYou planet.",
    "Why can't a nose be 12 inches long?\nBecause then it would be a foot.",
    "Did you hear about the restaurant on the moon?\nGreat food, no atmosphere.",
    "What do you call a fish wearing a bowtie?\nSophisticated.",
    "Why did the coffee file a police report?\nIt got mugged.",
    "I would avoid the sushi if I was you.\nIt's a little fishy.",
    "Want to hear a joke about paper?\nNever mind — it's tearable.",
    "What did the left eye say to the right eye?\nBetween you and me, something smells.",
    "I don't play soccer because I enjoy the sport.\nI'm just doing it for kicks.",
    "I'm terrified of elevators.\nI'm going to start taking steps to avoid them.",
    "What do you call a fake Irish stone?\nA sham rock.",
    "Why did the mushroom go to the party?\nBecause he was a fungi.",
    "I got hit in the head with a can of soda.\nLuckily it was a soft drink.",
    "What's a Jedi's favorite car?\nA Toyoda.",
    "How do you make holy water?\nYou boil the hell out of it.",
    "I told my wife she should embrace her mistakes.\nShe gave me a hug.",
    "Why do bees have sticky hair?\nThey use honeycombs.",
    "My boss told me to have a good day.\nSo I went home.",
    "What do you call an elephant that doesn't matter?\nAn irrelephant.",
    "Why couldn't the pony sing a lullaby?\nShe was a little horse.",
    "What's the best thing about Switzerland?\nI don't know, but the flag is a big plus.",
    "I'm so good at sleeping.\nI can do it with my eyes closed.",
    "Why don't scientists trust atoms?\nBecause they make up everything.",
    "How do you make 7 even?\nTake away the s.",
    "What do you call a group of disorganized cats?\nA cat-astrophe.",
    "Where do dads keep their jokes?\nIn a dad-a-base.",
    "What do you call a boomerang that won't come back?\nA stick.",
    "I accidentally handed my wife a glue stick instead of chapstick.\nShe's still not talking to me.",
    "What does a lemon say when it answers the phone?\nYellow!",
    "Why was 6 afraid of 7?\nBecause 7 ate 9.",
    "What do you call a snowman with a six-pack?\nAn abdominal snowman.",
    "Why do seagulls fly over the sea?\nBecause if they flew over the bay they'd be bagels.",
    "I used to hate facial hair,\nbut then it grew on me.",
    "What do you call a dog that can do magic?\nA Labracadabrador.",
    "Why did the tomato turn red?\nBecause it saw the salad dressing.",
    "How do trees get online?\nThey log in.",
    "What's orange and sounds like a parrot?\nA carrot.",
    "I don't trust trees.\nThey seem shady.",
    "Why did the man put his money in the blender?\nHe wanted to make liquid assets.",
    "I just watched a program about beavers.\nIt was the best dam program I've ever seen.",
    "Why can't you hear a pterodactyl go to the bathroom?\nBecause the P is silent.",
    "How do you make a water bed bouncier?\nUse spring water.",
    "What do you call a dinosaur with an extensive vocabulary?\nA thesaurus.",
    "Why did the invisible man turn down the job offer?\nHe couldn't see himself doing it.",
    "I used to be addicted to the hokey pokey,\nbut I turned myself around.",
    "What did one wall say to the other?\nI'll meet you at the corner.",
    "Why did the banana go to the doctor?\nIt wasn't peeling well.",
    "I ate a clock yesterday.\nIt was very time-consuming.",
    "What do you call a person with no body and no nose?\nNobody knows.",
    "Why was the math test so happy?\nIt had all the right angles.",
    "I told a chemistry joke.\nThere was no reaction.",
    "Why did the chicken go to the seance?\nTo get to the other side.",
    "What do you call a hat for your knee?\nA knee cap.",
    "My dog used to chase people on a bike.\nIt got so bad I had to take his bike away.",
    "Why did the picture go to jail?\nBecause it was framed.",
    "How does a penguin build its house?\nIgloos it together.",
    "I used to have a job at a calendar factory,\nbut I got fired for taking a day off.",
    "What's a skeleton's favorite instrument?\nA trom-bone.",
    "Why do vampires seem sick all the time?\nThey're always coffin.",
    "You know what the loudest pet is?\nA trumpet.",
    "What did the grape say when it got stepped on?\nNothing, it just let out a little wine.",
    "I cut my finger while chopping cheese.\nBut I think I'm grater.",
    "What's a haunted chicken?\nA poultry-geist.",
    "I told my wife she was the best thing that ever happened to me.\nShe said I should get out more.",
    "What did the big flower say to the little flower?\nHi, bud!",
    "Why did the student eat his homework?\nThe teacher said it was a piece of cake.",
    "What do you call a belt made of watches?\nA waist of time.",
    "I don't trust people who do acupuncture.\nThey're back stabbers.",
    "What do you call an alligator in a vest?\nAn investigator.",
    "Why did the melon jump into the pool?\nIt wanted to be a watermelon.",
    "How do you talk to a giant?\nUse big words.",
    "What did the drummer name his twin daughters?\nAnna 1, Anna 2.",
    "Why did the computer go to therapy?\nIt had too many bytes of emotional baggage.",
    "What's a foot's favorite snack?\nToe-st.",
    "I just found out I'm colorblind.\nThe news came out of the purple.",
    "Why can't you trust an atom?\nThey make up everything. Wait, I said that already.",
    "What do you call a camel with no humps?\nHumphrey.",
    "I named my dog 5 miles.\nSo I can tell everyone I walk 5 miles every day.",
    "What did the calculator say to the student?\nYou can count on me.",
    "Why did the stadium get so hot?\nAll the fans left.",
    "What's the difference between a guitar and a fish?\nYou can't tuna fish.",
    "I had a dream last night that I was a muffler.\nI woke up exhausted.",
    "What do you call a sad cup of coffee?\nA depresso.",
    "Why don't crabs give to charity?\nThey're shellfish.",
    "What did the janitor say when he jumped out of the closet?\nSupplies!",
    "How do you fix a broken pumpkin?\nWith a pumpkin patch.",
    "I told my friend 10 jokes to make him laugh.\nSadly, no pun in ten did.",
    "What do you call a fish with no eyes?\nWait, I already did that one. Never mind.",
    "Why did the phone go to school?\nIt wanted to improve its reception.",
    "What does a cloud wear under its raincoat?\nThunderwear.",
    "I used to work in a shoe recycling plant.\nIt was sole-destroying.",
    "Why did the pillow go to the doctor?\nIt was feeling a little down.",
    "What do you call a lazy kangaroo?\nA pouch potato.",
    "How do you make an octopus laugh?\nWith ten-tickles.",
    "What did the bread say to the butter?\nYou're on a roll.",
    "I asked the librarian if the library had any books on paranoia.\nShe whispered, 'They're right behind you.'",
    "Why did the can crusher quit his job?\nIt was soda pressing.",
    "What does a pirate pay for corn?\nA buccaneer.",
    "I tried to catch some fog yesterday.\nI mist.",
    "Why don't ants get lost?\nThey have great ant-ennas.",
    "What do you call a snake that builds houses?\nA boa constructor.",
    "Why did the man name his dogs Rolex and Timex?\nThey were watch dogs.",
    "What's the best way to watch a fly-fishing tournament?\nLive stream.",
    "I have a pencil that used to be owned by William Shakespeare.\nHe chewed it a lot. Now I can't tell if it's 2B or not 2B.",
    "What do you call a pony with a cough?\nA little horse.",
    "Why did the gym close down?\nIt just wasn't working out.",
    "What did the salad say to the fridge?\nShut the door, I'm dressing.",
    "How do you know if a joke is a dad joke?\nWhen it's fully groan.",
    "I finally watched that documentary about clocks.\nIt was about time.",
    "What's the best thing about elevator jokes?\nThey work on so many levels.",
    "Why did the sand dollar go to the bank?\nTo make a deposit.",
    "What do you call a Frenchman in sandals?\nPhilippe Philoppe.",
    "I used to be a banker.\nBut I lost interest.",
    "Why did the echo break up with the sound?\nIt just kept repeating everything.",
    "What's a tree's favorite drink?\nRoot beer.",
    "My friend said he knew a man with a wooden leg named Smith.\nI asked, 'What was the name of his other leg?'",
    "What do you call a magic owl?\nHoo-dini.",
    "Why was the broom late for work?\nIt over-swept.",
    "How do you make a lemon drop?\nJust let it fall.",
    "I don't find most horse jokes funny.\nBut the mane ones are ok.",
    "What do you call a knight who is afraid to fight?\nSir Render.",
    "Why did the light bulb fail its exam?\nIt wasn't very bright.",
    "What do you get when you cross a snowman and a vampire?\nFrostbite.",
    "I told my plants a joke about photosynthesis.\nThey loved it. They were glowing with smiles.",
    "What did one plate whisper to the other?\nDinner's on me.",
    "Why did the chicken join a band?\nIt already had drumsticks.",
    "What do you call a bear caught in the rain?\nA drizzly bear.",
    "I once dated a girl who was a tennis player.\nLove meant nothing to her.",
    "Why can't your nose be 12 inches long?\nBecause then it would be a foot. Yes, I recycled that one on purpose.",
    "What did the painter say to the wall?\nOne more crack and I'll plaster you.",
    "How do you get a squirrel to like you?\nAct like a nut.",
    "Why did the baker have smelly hands?\nBecause he kneaded a poo.",
    "What's a balloon's least favorite type of music?\nPop.",
    "I used to be a pilot.\nBut I couldn't land the job.",
    "What do you call a cow with two legs?\nLean beef.",
    "Why did the candle break up with the match?\nIt found someone hotter.",
    "What did one eye say to the other?\nDon't look now, but something between us smells.",
    "I made a belt out of old wristwatches.\nIt was a complete waist of time.",
    "Why don't some couples go to the gym?\nBecause some relationships don't work out.",
    "What's brown and sounds like a bell?\nDung.",
    "Why was the math book so miserable?\nIt was full of problems. Still true.",
    "What do you call a snowman that tells tall tales?\nA snow-fake.",
    "I told a joke to my toaster.\nIt didn't laugh, but it did give me the warmest smile.",
    "What did the hat say to the scarf?\nYou hang around while I go on ahead.",
    "Why did the toilet paper roll down the hill?\nTo get to the bottom.",
    "What did the dirt say to the rain?\nIf this keeps up, my name is mud.",
    "I keep trying to lose weight.\nBut it keeps finding me.",
    "What do you call a cheetah that won the lottery?\nA spotted millionaire.",
    "Why don't skeletons ever win arguments?\nThey don't have a leg to stand on. Or any guts.",
    "What did the tie say to the hat?\nYou go on ahead. I'll hang around.",
    "How do you throw a space party?\nYou planet. And I'm telling you again.",
    "What do you get when you cross a joke with a rhetorical question?",
    "I wasn't originally going to get a brain transplant.\nBut then I changed my mind.",
    "What do you call a sleeping dinosaur?\nA dino-snore.",
    "Why did the astronaut break up with his girlfriend?\nHe needed space.",
    "What's the least spoken language?\nSign language.",
    "I had to sell my vacuum cleaner.\nIt was just gathering dust.",
    "What do you call a pig that's been set on fire?\nBakon.",
    "Why did the duck get arrested?\nFor selling quack.",
    "What did the baby corn say to the mama corn?\nWhere's pop corn?",
    "I'm writing a book about reverse psychology.\nDon't read it.",
    "How do you find Will Smith in the snow?\nLook for the fresh prints.",
    "What do you call a toothless bear?\nA gummy bear. Wait—",
    "Why did the golfer bring an extra pair of socks?\nIn case he got a hole in one.",
    "I keep hitting the spacebar on my keyboard.\nBut I'm still on Earth.",
    "What do you call a sheep with no legs?\nA cloud.",
    "Why did the picture frame break up with the painting?\nIt felt boxed in.",
    "I told my wife I'd fix the doorbell.\nShe said I never ring true.",
    "What's a skeleton's favorite snack?\nSpare ribs.",
    "How do you tell if a vampire is sick?\nBy how much he's coffin.",
    "Why did the computer keep sneezing?\nIt had a virus.",
    "What do you call a man who can't stand?\nNeil.",
    "I bought a boat because I wanted to be more nautical.\nIt was a pier pressure thing.",
    "Why did the clock go to the principal's office?\nIt kept tocking back.",
    "What do you call a dolphin with a sunburn?\nA blistered sister.",
    "I entered a pun competition.\nI submitted ten entries, hoping one would win. But no pun in ten did.",
    "What did the grape do when the elephant sat on it?\nIt let out a little wine.",
    "Why did the peanut get kicked out of the park?\nIt was a-salted.",
    "What do you call an apology written in dots and dashes?\nRemorse code.",
    "I tried to make a chemistry joke.\nThe solution never crystallized.",
    "How does the moon cut his hair?\nEclipse it.",
    "What did the cucumber say to the pickle?\nYou're in a real brine situation.",
    "Why can't a bicycle stand on its own?\nIt's two-tired. Still.",
    "I got a new job at a bakery.\nI kneaded the dough.",
    "What do you call a fly with no wings?\nA walk.",
    "Why was the calendar always so popular?\nIt had a lot of dates.",
    "What did the guitar say to the musician?\nDon't fret.",
    "I'm reading a horror novel in Braille.\nSomething bad is about to happen. I can feel it.",
    "What do you call a boomerang that doesn't work?\nA stick. Again.",
    "Why was the baseball player such a hothead?\nHe kept hitting foul balls.",
    "How do you make a Swiss roll?\nPush him down a hill.",
    "What do you call a donkey with only three legs?\nA wonky donkey.",
    "I used to think I was indecisive.\nBut now I'm not so sure.",
    "What's Forrest Gump's password?\n1forrest1.",
    "Why did the cookie cry?\nIts mother was a wafer so long.",
    "What do you get when you cross an umbrellas?\nWet.",
    "I wondered why the baseball kept getting bigger.\nThen it hit me.",
    "What's the difference between a poorly dressed man on a tricycle and a well-dressed man on a bicycle?\nAttire.",
    "Why did the frog take the bus?\nHis car got toad.",
    "What do you call a line of rabbits hopping backwards?\nA receding hare line.",
    "I got carded at the liquor store.\nMy Blockbuster card somehow confused the cashier.",
    "Why can't you run through a campground?\nYou can only ran, because it's past tents.",
    "What did one casket say to the other?\nIs that you, coffin?",
    "I stayed up all night wondering where the sun went.\nThen it dawned on me.",
    "What do you call a fake noodle?\nStill an impasta.",
    "Why did the worker get fired from the orange juice factory?\nLack of concentration.",
    "How does a farmer count his cows?\nWith a cow-culator.",
    "What's red and bad for your teeth?\nA brick.",
    "I used to be a lumberjack.\nI couldn't hack it.",
    "What do you call a deer with no eyes?\nNo eye-deer.",
    "What do you call a deer with no eyes and no legs?\nStill no eye-deer.",
    "What do you call a deer with no eyes, no legs, and no genitals?\nStill no f---ing eye-deer.",
    "Why did the tomato blush?\nIt saw the salad dressing. Again.",
    "My friend said, 'You'll never guess what happened to me today.'\nI said, 'Try me.' He said, 'No, I really think you'll never guess.'",
    "What do you call a fish wearing a crown?\nA king mackerel.",
    "I gave up my seat to a blind person on the bus.\nThat's how I lost my bus driver job.",
    "What do you call a can opener that doesn't work?\nA can't opener.",
    "Why don't scientists trust atoms?\nI already told you — they make up everything.",
    "What did the digital clock say to its mother?\nLook, ma — no hands!",
    "How do you fix a broken tomato?\nTomato paste.",
    "What do you call a factory that makes okay products?\nA satisfactory. I said that one too.",
    "I ate a dictionary for breakfast.\nIt was a novel experience.",
    "Why did the whale cross the ocean?\nTo get to the other tide.",
    "What's a ghost's favorite fruit?\nBoo-berries.",
    "I don't trust stairs.\nI said it before, they're always up to something.",
    "What do you call a woman standing on a tennis court?\nAnnette.",
    "How do you make a tissue dance?\nWe've covered this — a little boogie in it.",
    "Why couldn't the bicycle find its way home?\nIt lost its bearings.",
    "What did the policeman say to his belly button?\nYou're under a vest.",
    "I'm very good at trivia.\nIn fact, I know the complete works of Shakespeare like the back of my hand. What's the play? No idea. What's on the back of my hand? Also no idea.",
    "What does a baker say when he wins the lottery?\nI'm on a roll.",
    "Why did the banana get a divorce?\nIt found a bunch of reasons.",
    "What did the mother rope say to the baby rope?\nDon't be knotty.",
    "I went to a zoo and the only animal there was a dog.\nIt was a Shih Tzu.",
    "How many tickles does it take to make an octopus laugh?\nTen-tickles. Still.",
    "What do you call a dog magician?\nA Labracadabrador. We had this one.",
    "Why did the pelican get kicked out of the restaurant?\nHe had a very big bill.",
    "I told my wife she was overreacting.\nShe said, 'I'm not overreacting!' Then she calmed down.",
    "What's the difference between ignorance and apathy?\nI don't know and I don't care.",
    "Why did the cat sit on the computer?\nTo keep an eye on the mouse.",
    "What did one snowman say to the other?\nDo you smell carrots?",
    "I'm addicted to brake fluid.\nBut I can stop anytime.",
    "What did the beaver say to the tree?\nIt's been nice gnawing you.",
    "Why did the toilet go to therapy?\nIt kept holding things in.",
    "What do you call a dog that can tell time?\nA watch dog.",
    "I told my son to stop doing Flash impressions.\nHe said, 'But Dad, I was born for this role.'",
    "What's E.T. short for?\nHe's only got little legs.",
    "Why did the mirror get detention?\nIt kept reflecting badly on everyone.",
    "What does a pirate say while eating sushi?\nYo ho ho and a bottle of soy.",
    "I wonder what my grandad would think if he could see me now.\nProbably nothing, he's been dead 20 years.",
    "Why do trees hate tests?\nThey always get stumped.",
    "What do you call a bird that sticks to everything?\nA Vel-crow.",
    "My wife asked me to sync her phone.\nSo I threw it into the ocean. Now her phone and the ocean are in sync.",
    "What's red and moves up and down?\nA tomato in an elevator.",
    "Why did the leaf go to the doctor?\nIt was feeling green.",
    "What do cows read in the morning?\nThe moos-paper.",
    "I was going to tell a time travel joke.\nBut you didn't like it.",
    "Why can't you give Elsa penicillin?\nBecause the cold never bothered her anyway, but the allergy does.",
    "What did the buffalo say to his son when he left for college?\nBison.",
    "How do you know a joke is truly a dad joke?\nThe punchline is a parent.",
    "I told my wife I was going to build a car out of spaghetti.\nShe said, 'You're pasta point of no return.'",
    "What did the left butt cheek say to the right?\nTogether, we make a great pair.",
    "Why don't eggs tell secrets?\nThey'd crack under pressure.",
    "I sold my vacuum the other day.\nIt was just collecting dust anyway.",
    "What do you call a happy camper?\nA jamboree.",
    "What's the difference between a hippo and a Zippo?\nOne's really heavy, the other's a little lighter.",
    "Why did the scarecrow get a promotion?\nHe was outstanding in his field. We really did this one.",
    "I used to hate math.\nBut then I realized, it all adds up.",
    "What do you call a snowman party?\nA snowball.",
    "Why did the foot go to the party alone?\nIt couldn't find a sole mate.",
    "What does bread do after it's baked?\nIt loafs around.",
    "I've decided to sell my Hoover.\nIt was just collecting dust.",
    "What do you call a security guard working at Samsung?\nA Guardian of the Galaxy.",
    "Why did the pie go to the dentist?\nIt needed a filling.",
    "I wrote a song about a tortilla.\nActually, it's more of a wrap.",
    "What did the mother broom say to her children?\nIt's time to go sweep.",
    "Why do Swedish warships have barcodes?\nSo when they dock they can scan-da-navy-in.",
    "I bought a cheap pair of shoes from a drug dealer.\nI don't know what he laced them with, but I've been tripping all day.",
    "What's the leading cause of dry skin?\nTowels.",
    "How does a rabbi make coffee?\nHebrews it.",
    "What did the traffic light say to the car?\nDon't look, I'm about to change.",
    "My girlfriend broke up with me because of my hair loss.\nIt's ok though. I'm starting to grow past it.",
    "What do you call an ugly potato?\nA spec-tater.",
    "Why did the kid bring a ladder to school?\nHe wanted to go to high school.",
    "I told a joke about a ceiling once.\nIt went over everyone's head.",
    "What's the difference between a cat and a comma?\nOne has claws at the end of its paws, the other is a pause at the end of a clause.",
    "My wife is mad I have no sense of direction.\nSo I packed up and right.",
    "Why did the fire truck go to school?\nTo become a little brighter.",
    "What do you call a nun who sleepwalks?\nA roaming Catholic.",
    "I hate how funerals are always at 9 or 10 in the morning.\nI'm not a mourning person.",
    "What's the hardest part of a vegetable to eat?\nThe wheelchair.",
    "Why did the ballerina quit?\nShe couldn't find her pointe.",
    "I have a fear of speed bumps.\nBut I'm slowly getting over it.",
    "What do you call a sad strawberry?\nA blueberry.",
    "Why did the bike fall asleep?\nIt was two tired. I know, it's the third time.",
    "What's a tornado's favorite game?\nTwister.",
    "My uncle was crushed by a pile of books.\nHe's in a stable condition now. Only has his shelf to blame.",
    "What did one flag say to the other?\nNothing, it just waved.",
    "Why did the chicken hold a seance?\nTo get to the other side. We did this.",
    "What do you call a magician who's lost his magic?\nIan.",
    "I used to be a shepherd.\nBut I couldn't find the silver lining.",
    "How much does a hipster weigh?\nYou probably haven't heard of the scale.",
    "What did the sushi say to the bee?\nWasabi!",
    "Why did the banana put sunscreen on?\nBecause it was peeling.",
    "I gave all my dead batteries away.\nThey were free of charge.",
    "What do you call a triangle that's bad at sports?\nA wrecked-angle.",
    "Why are there gates around cemeteries?\nPeople are dying to get in.",
    "I used to be a baker.\nBut I didn't make enough dough.",
    "What's the difference between roast beef and pea soup?\nAnyone can roast beef.",
    "How do you make a Kleenex dance?\nBoogie. We. Did. This.",
    "Why did the football team go to the bakery?\nThey needed a good roll.",
    "What do you call a sheep with no head or legs?\nFluff.",
    "I got a universal remote for Christmas.\nI thought, 'This changes everything.'",
    "What did the zero say to the eight?\nNice belt.",
    "Why was the computer cold?\nSomeone left Windows open.",
    "What do you call a mule with a cold?\nA stubborn donkey with a runny nose.",
    "I hate Russian dolls.\nThey're so full of themselves.",
    "Why don't eggs tell jokes?\nThey might crack up. We did this one.",
    "What's brown and sounds like a bell?\nDung. I know, I said it.",
    "How do you make a mobile phone sound Scottish?\nThrow it in a loch.",
    "What do you call a dinosaur with one eye?\nA do-you-think-he-saurus.",
    "I told my wife she should do lunges.\nThat would be a big step forward. Now I'm repeating myself.",
    "Why did the orange lose the race?\nIt ran out of juice.",
    "What's the difference between a poorly dressed man and a well-dressed man?\nA tire.",
    "My wife accused me of being a bad mime.\nIt was the worst thing that's never happened to me.",
    "What do you call a duck that steals?\nA robber ducky.",
    "Why did the man stare at the orange juice container?\nIt said concentrate.",
    "What does the man in the moon do when his hair gets too long?\nEclipse it.",
    "I put a skylight in my apartment.\nThe people upstairs are furious.",
    "What do you call a chicken in a shellsuit?\nAn egg.",
    "Why don't calculus students throw parties?\nBecause there's no limit.",
    "I bought a ceiling fan.\nComplete waste of money. He just stands there, saying he's a big fan.",
    "What did the salt say to the pepper?\nSeason's greetings.",
    "What do you call a doctor who fixes websites?\nA URL-ologist.",
    "Why did the astronaut take a lawnmower to the moon?\nHe wanted to mow-dule the surface.",
    "I can't believe I got fired from the calendar factory.\nAll I did was take a day off. I said this.",
    "What do you call an expert fisherman?\nA master baiter.",
    "Why did the bicycle fall over?\nBecause it was two-tired. Is there an echo?",
    "What's a frog's favorite kind of music?\nHip hop.",
    "I don't enjoy computer jokes.\nNot one bit.",
    "Why don't seagulls fly over bays?\nBecause then they'd be bagels. We did this.",
    "What do you call a ghost with a broken leg?\nHoblin.",
    "My dad said I'd never be as good at video games as him.\nI said, 'That's a low bar.'",
    "How do you make a hot dog stand?\nSteal its chair.",
    "What did one hat say to the other?\nYou stay here, I'll go on a head.",
    "I used to be a banker, but I lost interest.\nI already said this one.",
    "Why did the paper go to school?\nIt wanted to be a little more tearable.",
    "What do you call a dog in a phone booth?\nA Golden Receiver.",
    "Albert Einstein was 23 when he started working at the patent office.\nAnd 24 when he realized the patent for the time machine was already taken.",
    "What's the difference between a cat and a complex sentence?\nA cat has claws at the end of its paws. A complex sentence has a pause at the end of its clause. I really like this one.",
    "Why did the balloon go to the psychologist?\nIt had too much pressure and might pop.",
    "What do you call a bear with no ears?\nB.",
    "What do you call a bear with no ears and no teeth?\nA gummy B.",
    "I lost my job as a cricket commentator.\nI kept saying 'Howzat' instead of 'How is that'.",
    "Why was the mushroom always invited to parties?\nHe's a fungi. Same.",
    "What do you call a man with a shovel?\nDoug.",
    "What do you call a man without a shovel?\nDouglas.",
    "I can cut a piece of wood just by looking at it.\nIt's true. I saw it with my own eyes.",
    "What's the difference between a good joke and a bad joke timing.",
    "Why did the belt get arrested?\nIt held up a pair of pants.",
    "What do you call a can of soda that's been blessed?\nHoly water.",
    "I put a bet on a horse that was 10-to-1.\nIt was due to run at 3:30. The horse didn't move until 4. Good maths.",
    "What do you call a goat with a trumpet?\nBilly the Kid.",
    "Why don't you ever see hippos hiding in trees?\nBecause they're really good at it.",
    "I started a new job as a delivery driver for a fruit company.\nI've been given a van, a round, and two melons.",
    "What do you do when you see a spaceman?\nPark your car, man.",
    "My memory is so bad.\nI once called my wife by the wrong name. She said, 'Who's that?' I said, 'I can't remember.'",
    "Why did the computer go to the dentist?\nIt had Bluetooth.",
    "What do you call a fish who practices medicine?\nA sturgeon.",
    "My pen broke.\nNow I can't draw any conclusions.",
    "What time do you go to the dentist?\nTooth-hurty. Classic dad.",
    "How many ears does Captain Kirk have?\nThree. The left ear, the right ear, and the final front ear.",
    "Why did the man buy four horses?\nHe wanted to get a stable connection.",
    "What do you call it when a dinosaur crashes his car?\nTyrannosaurus wrecks.",
    "I poured root beer into a square glass.\nNow it's just beer.",
    "Why did the cat wear a fancy dress?\nShe wanted to look purr-fect.",
    "What do you call a dinosaur that's asleep?\nA dino-snore. I said this one.",
    "I used to date a baker.\nBut she was too kneady.",
    "Why did the boy take a hammer to bed?\nHe wanted to hit the hay.",
    "What do you call the wife of a hippo?\nA hippopotamissus.",
    "I got fired from the transmission shop.\nI was told I didn't make the shift.",
    "What's the difference between a literalist and a kleptomaniac?\nA literalist takes things literally. A kleptomaniac takes things, literally.",
    "Why did the lamp go to school?\nTo get brighter.",
    "What do you call a person in a tree with a briefcase?\nA branch manager.",
    "I couldn't figure out why the baseball kept getting bigger.\nThen it hit me. I already said this.",
    "Why did the baguette go to the bank?\nTo get some dough.",
    "What do you get when you combine a rhetorical question and a joke?",
    "My doctor told me I'm going deaf.\nI said, 'Can you speak up? I'm going deaf.' He said, 'You're going deaf.' I said, 'What?'",
    "What do you call a Frenchman wearing sandals?\nPhilippe Philoppe. Encore.",
    "What did the math book say to the guidance counselor?\n'Help me. I have so many problems.'",
    "I invented a new word: plagiarism.",
    "Why did the M&M want to go to school?\nBecause it wanted to be a Smartie.",
    "What's the difference between Dubai and Abu Dhabi?\nThe people in Dubai don't like the Flintstones. But the people in Abu Dhabi do.",
    "I accidentally sprayed deodorant in my mouth.\nNow I have 24-hour protection against speaking.",
    "What do you call a laughing motorcycle?\nA Yamahahaha.",
    "I gave my friend an elephant for his room.\nHe said, 'Thanks.' I said, 'Don't mention it.'",
    "Why don't astronauts get married?\nBecause they need their space.",
    "What do you get when you cross a centipede with a parrot?\nA walkie-talkie.",
    "Did you hear about the guy who invented the knock-knock joke?\nHe won the no-bell prize.",
    "Why did the old man put his money in the blender?\nHe wanted liquid assets. Done this.",
    "What do you call a cow with three legs?\nTri-tip.",
    "What do you call a cow with no legs at all?\nGround beef. Again.",
    "What do you call a cow with one leg?\nSteak.",
    "Why did the light bulb go to school?\nIt wanted to be a little brighter.",
    "My friend said, 'I've been asked to lead the orchestra.'\nI said, 'That's a big ask.' He said, 'I know. But I'll always conduct myself properly.'",
    "What's the best time to go to the dentist?\nTooth-hurty. I wonder if this joke is popular enough to tell three times.",
    "Why can't a bike stand up by itself?\nI've answered this. It's two-tired.",
    "What do you call a book club that's stuck on one book?\nChurch.",
    "I wanted to be a history teacher.\nBut I couldn't see a future in it.",
    "Why did the ghost go to the bar?\nFor the boos.",
    "What did the mother bullet say to the father bullet?\nWe're going to have a BB.",
    "Why did the burglar take a shower?\nHe wanted to make a clean getaway.",
    "I've got a friend who's a professional billiards player.\nHe says it's just a series of fortunate cues.",
    "What do you call a rich elf?\nWelfy.",
    "Why did the fisherman always tell jokes?\nHe wanted to be a real Master Baiter.",
    "I asked my wife what exercise she was doing.\nShe said, 'The plank.' So I slammed a wooden plank on the floor and watched. She wasn't happy.",
    "What do you call singing Lincolns?\nAbe acapella.",
    "Why did the farmer bury his money?\nTo keep it in a safe de-purse-it.",
    "What do you call an insect on the moon?\nA lunar tick.",
    "I decided to give my money to charity.\nNow I just need to find a charity called 'Rent'.",
    "Why don't mummies take vacations?\nThey're afraid to unwind.",
    "What do you call a nervous javelin thrower?\nShakespeare.",
    "How do dogs pay for things?\nWith pup-currency.",
    "I hate it when people make spelling mistakes.\nIts the worst.",
    "What do you call 50 pigs and 50 deer?\nA hundred sows and bucks.",
    "What did one sea say to the other?\nNothing, it just waved. — Wait, already used that.",
    "I told my wife she should be more positive.\nShe said, 'I'm positive you talk too much.'",
    "Why did the robot go on vacation?\nTo recharge.",
    "What do you call a well-balanced horse?\nStable.",
    "My dad told me to invest my money in bonds.\nSo I bought $300 worth of James Bond DVDs.",
    "What's a frog's favorite candy?\nLollihops.",
    "Why did the crossing guard retire?\nHe couldn't control the crossing anymore.",
    "What do you call a pencil with two erasers?\nPointless.",
    "I couldn't find my scissors yesterday.\nThen I thought, 'This is getting out of hand.'",
    "What did Delaware?\nA New Jersey.",
    "Why did the key go to therapy?\nIt kept getting locked out.",
    "What's a tree's least favorite month?\nSep-timber.",
    "My dad taught me everything I know about money.\nFor example, I thought '401k' was a marathon.",
    "Why did the painting go to jail?\nIt was framed. Again.",
    "What do you get when you cross a snake and a pie?\nA python-thon.",
    "What did the paperclip say to the magnet?\nI find you very attractive.",
    "Why did the coffee go to the police?\nIt got mugged. Again.",
    "I used to have a fear of hurdles.\nBut I got over it.",
    "What do you call a man with no shins?\nTony.",
    "What do you call a man with no shins and no knees?\nNiel.",
    "Why did the CD go to school?\nTo get burned.",
    "What do you get when you cross a joke with a rhetorical question?\n...",
    "Did you hear about the bakery that caught fire?\nThe business is toast.",
    "I told my wife I was leaving her because of her obsession with pasta.\nShe said, 'Can you be more pacific?'",
    "What do you call a train made of bubble gum?\nA chew-chew train.",
    "I just read a book about Mount Everest.\nThe ending was a real cliffhanger.",
    "What's the difference between a teacher and a train?\nA teacher says, 'Take out your gum.' A train says, 'Chew, chew!'",
    "Why did the dictionary go to school?\nTo find its meaning.",
    "What do you call a priest who's a lawyer?\nFather-in-law.",
    "I used to be a nun.\nI had a bad habit.",
    "What do you call a boomerang that won't come back?\nWe've established: a stick.",
    "I'm not a complete idiot.\nSome parts are missing.",
    "Why did the chicken go to KFC?\nTo see a chicken strip.",
    "What did the pencil sharpener say to the pencil?\nStop going in circles.",
    "I used to hate facial hair.\nThen it grew on me. Already done.",
    "Why can't you play cards on a spaceship?\nThe commander's standing on the deck.",
    "What do you call a snake that's 3.14 meters long?\nA pi-thon.",
    "My wife told me to stop impersonating a flamingo.\nSo I had to put my foot down.",
    "What do you call an Argentinian who's lost his car?\nCarlos.",
    "Why did the sprinter retire?\nBecause he ran out of time.",
    "I named my dog 'Twenty Pence'.\nSo I can tell people I have twenty pence and a dog.",
    "What do you call a shoe made of banana?\nA slipper.",
    "Why did the football manager go to the bank?\nTo get his quarter back.",
    "I'm reading a book about teleportation.\nIt's bound to take me places.",
    "What do you call a pig with a cold?\nA-choo-choo train? No, just a sick pig.",
    "Why did the train eat its lunch?\nBecause it had a loco-motive.",
    "What do you call a bee that can't make up its mind?\nA maybe.",
    "I told a joke to a glass of water.\nIt went right through.",
    "What's a balloon's least favorite genre?\nPop music.",
    "Why did the toilet go to the party?\nBecause it's always the life of the bowl.",
    "What do you call a French pig?\nPorque.",
    "I used to work for a soft drink company.\nBut I couldn't concentrate.",
    "Why did the egg hide?\nIt was a little chicken.",
    "What's brown and sticky?\nA twig. Wait, no, the original was better.",
    "Why did the policeman smell so bad?\nHe was on duty.",
    "What do you get when you mix a joke with a rhetorical question?\nI've asked this three times now.",
    "I told my reflection I'm the fairest of them all.\nIt cracked up.",
    "What did the cloud do when it failed its exam?\nIt rained on its parade.",
    "How do you catch an entire school of fish?\nWith book-bait.",
    "Why was the sand wet?\nBecause the sea weed.",
    "I don't know what the best thing about Switzerland is.\nBut the flag is definitely a big plus. Done this.",
    "What do you call a dentist who doesn't like tea?\nDenis.",
    "Why do melons have weddings?\nBecause they cantaloupe.",
    "I went to a restaurant that serves breakfast at any time.\nSo I ordered French toast during the Renaissance.",
    "What do you call an elephant that flies?\nA jumbo jet.",
    "Why are elevator jokes so good?\nThey work on so many levels. I said this.",
    "What do you call a rude potato?\nA dictator.",
    "How does a blizzard say goodbye?\nIt gives a cold shoulder.",
    "Why can't you trust stairs?\nThey're always up to something. I KNOW.",
    "What did the flower say after it told a joke?\nI was just pollen your leg.",
    "I can't believe I made this joke list.\nIt's 500 jokes long and half of them are repeats about stairs and tired bicycles.",
    "What do you call a fish that wears a bowtie?\nSophisticated. I know I said this.",
    "Why did the cookie go to the doctor?\nIt was feeling crumby.",
    "I used to run a dating service for chickens.\nBut I was struggling to make hens meet.",
    "What's the best way to carve wood?\nWhittle by whittle.",
    "I asked the surgeon if I could administer my own anesthetic.\nHe said, 'Go ahead — knock yourself out.'",
    "Why did the belt go to jail?\nIt held up a pair of pants. Again.",
    "What's a pirate's favorite letter?\nYou'd think it's R, but his first love is the C.",
    "What's a pirate's favorite vegetable?\nArrrr-tichoke.",
    "Which person do you take to a party that smells?\nNobody. You take a shower.",
    "I broke my finger at the bowling alley.\nIt was a real turkey.",
    "Why don't blind people go skydiving?\nIt scares the dog.",
    "What do you call a monkey that won't share?\nA baboon.",
    "I used to have a job at a recycling center.\nI had to can it.",
    "Why did the watch go to space?\nTo find some time.",
    "What do you call a dinosaur with a sleep disorder?\nA brontosnore-us.",
    "What do you call a man with no arms and no legs in a pool?\nBob.",
    "What do you call a man with no arms and no legs on a wall?\nArt.",
    "What do you call a man with no arms and no legs in a hole?\nPhil.",
    "What do you call a man with no arms and no legs in a pile of leaves?\nRussell.",
    "What do you call a dog with no legs?\nIt doesn't matter — he won't come anyway.",
    "Why did the vampire read the newspaper?\nHe heard it had great circulation.",
    "What do you call a pig with laryngitis?\nDisgruntled.",
    "I told my wife I have a genetic condition.\nShe said, 'You never mentioned that before.' I said, 'It's hereditary.'",
    "Why was the tomato so good at sports?\nIt knew how to ketchup.",
    "What do you call a potato at a baseball game?\nA spec-tater. Done this one.",
    "Why did the deer need braces?\nHe had buck teeth.",
    "How does Moses make coffee?\nHebrews it. Already said this.",
    "I told my doctor I broke my arm in two places.\nHe told me to stop going to those places.",
    "What do you call a steak that's been knighted?\nSir Loin.",
    "Why did the orange go to school?\nTo get its juice-tification.",
    "What did the fish say when it hit a wall?\nDam.",
    "I used to be a baker.\nThe hardest part is making enough dough. Heard this.",
    "Why don't scientists trust atoms?\nI've said this four times now. They make up everything!",
    "What did the baby corn say to its mom?\n'Where's pop corn?' Yes, I did this one.",
    "I've started a new business making yachts in my attic.\nSails are through the roof.",
    "What's the difference between a poorly dressed man and a bicycle?\nOne has a tire and the other is too tired.",
    "What do you call a sheep that can't sleep?\nA sheep-counting failure.",
    "Why did the deck of cards go to therapy?\nIt had a full house of issues.",
    "What do you call a sad lion?\nA cryin' king.",
    "I once dated a girl named Ruby.\nOur relationship was a gem. Then she took me for granite.",
    "Why did the chicken stop in the middle of the road?\nIt wanted to lay it on the line.",
    "What did the mom say to the crying math book?\n'Stop your problems, you're being irrational.'",
    "I can't stand being in a wheelchair.\nBut I'm slowly getting over it. Different setup from the speed bump one.",
    "Why did the painter go to jail?\nHe was framed.",
    "What do you call a camel that's been knighted?\nSir Camelot.",
    "I went to buy some camouflage trousers.\nCouldn't find any.",
    "What did the digital clock do when it was hungry?\nIt went back four seconds.",
    "Why did the bacteria fail the exam?\nHe was a little culture-shocked.",
    "I told my wife I'd stop drinking.\nBut I'm not a quitter.",
    "What's the difference between an onion and a bagpipe?\nNobody cries when you chop up a bagpipe.",
    "Why did the coffee call the police?\nIt got mugged. Again and again.",
    "What do you call a murderer with two legs?\nA homocide.",
    "What do you call a murderer with no legs?\nA homocide on the floor.",
    "I bought a world map, gave my wife a dart, and said, 'Throw this and wherever it lands, I'll take you.'\nWe're going to spend two weeks behind the fridge.",
    "Why did the math book look so sad?\nStop asking — it has too many problems.",
    "What did one ocean say to the other ocean?\nNothing, they just waved. I keep doing this.",
    "How do you start a teddy bear race?\nReady, teddy, go.",
    "Why did the girl bring a pencil to bed?\nShe wanted to draw the curtains.",
    "What do you call a cow that just gave birth?\nDe-calf-inated.",
    "My wife said I was the cheapest person she's ever met.\nI said, 'That's not true.' She said, 'Name one expensive thing you own.' I said, 'I can't right now, I'm thinking.'",
    "Why did the astronaut break up with the alien?\nThere was no chemistry.",
    "What do you call 100 rabbits walking backwards?\nA receding hare line. Had this.",
    "I thought about going on an all-almond diet.\nBut that's just nuts.",
    "What did the red light say to the green light?\nI'd love to stay, but I've got to change.",
    "Why did the skeleton go to the party alone?\nHe had no body to go with.",
    "What do you get if you cross a cow and a duck?\nMilk and quackers.",
    "I'm so good at telling dad jokes.\nIt's how eye roll.",
    "What did the blanket say to the bed?\nDon't worry, I've got you covered.",
    "Why can't you trust an acrobat?\nThey're always flipping out.",
    "What did the shrimp say to the crab?\nYou're so shellfish.",
    "I entered a joke competition.\nThe prize was $10,000. I sent in ten jokes. Again, no pun in ten did.",
    "What did the paper say to the pen?\nI dot my i's on you.",
    "Why did the phone keep dropping calls?\nIt had bad reception.",
    "What do you call a snowman in July?\nA puddle.",
    "How do you make a goldfish age?\nTake away the g.",
    "What do you call a pencil with no lead?\nPointless. Already did this one.",
    "I've been told I'm condescending.\nThat means I talk down to people.",
    "Why did the bird go to the hospital?\nIt needed tweetment.",
    "What did the salad say to the dressing?\nYou complete me.",
    "I don't always tell dad jokes.\nBut when I do, he laughs.",
    "What's orange and sounds like a parrot?\nA carrot. Again.",
    "Why did the rubber duck cross the road?\nTo get to the other tub.",
    "What do you call an elephant that doesn't share?\nSelfish-ant.",
    "I told my wife she was the most beautiful woman in the world.\nShe said, 'What about all those models?' I said, 'They're a different scale.'",
    "What's the difference between a poorly dressed sandwich and a well-dressed sandwich?\nLettuce.",
    "Why was the computer so good at music?\nIt had perfect pitch.",
    "What did one snowflake say to the other?\n'You're one of a kind.' 'No, YOU'RE one of a kind.'",
    "I've been thinking about taking up meditation.\nBut then I thought, 'Nah, that's overthinking it.'",
    "Why can't you give a cat a laptop?\nThey'd hack it with their claws.",
    "What do you call a game of tag between two volcanoes?\nLava at first sight.",
    "I went to the doctor and said, 'Doctor, I've broken my arm.'\nHe said, 'Don't do that.'",
    "Why did the chicken go to the library?\nTo check out a bawk.",
    "What do you call a bee that lives in America?\nUSB.",
    "Why did the shoe go to school?\nTo get a little more sole.",
    "I told my wife she should do more sit-ups.\nShe said, 'I do plenty.' I said, 'Name one.' She couldn't.",
    "What do you get when you cross a snowman and a dog?\nFrostbite. I did this already but with a vampire.",
    "Why was the broom running late?\nHe over-swept. Done.",
    "What's the difference between a poorly dressed man on a unicycle and a well-dressed man on a bike?\nAttire. We did this.",
    "I keep having dreams about being a muffler.\nI wake up exhausted. Still happening.",
    "How do you follow Will Smith in the snow?\nYou follow the fresh prints. I said this too.",
    "What do you call a man with a car on his head?\nJack.",
    "What do you call a woman with a cat on her head?\nKitty.",
    "What do you call a child with a vacuum on their head?\nDusty.",
    "I was at a restaurant and the waiter said, 'Do you want a box for your leftovers?'\nI said, 'No, but I'll wrestle you for it.'",
    "Why did the phone book go to therapy?\nIt had too many issues.",
    "What's a foot's favorite food?\nToe-st.",
    "Why did the music teacher go to jail?\nShe had too many bad notes.",
    "What did the coffee say to the donut?\nGlaze to meet you.",
    "I told my friend I was starting a boat business.\nHe said, 'That sounds like a lot of pier pressure.' I said, 'I can handle the current.'",
    "What do you call a bug that can't stop talking?\nA chatterpillar.",
    "Why did the broom get bad grades?\nIt kept sweeping things under the rug.",
    "What's the difference between a poorly dressed man and a calendar?\nOne has dates, the other has no dates.",
    "I hate when people tell me 'Carpe Diem.'\nEvery time I just think, 'Carpet Diem.' That's a whole different thing.",
    "What do you call a nosy pepper?\nJalapeno business. Classic.",
    "Why did the grape stop in the middle of the road?\nIt ran out of juice. Orange variant.",
    "What's a skeleton's favorite song?\n'Bad to the Bone.'",
    "I used to be a pilot, but I kept getting air-sick.\nNow I'm a ground control major Tom.",
    "Why did the student bring a ladder to class?\nHe wanted to go to high school. Already said.",
    "What do you call a sleeping dinosaur?\nDino-snore. We had this.",
    "Why don't you ever see a hippo hiding in a tree?\nBecause they're very good at it. I know I said this.",
    "I told my girlfriend she's the most beautiful girl in the world.\nShe said, 'Really?' I said, 'No, but I had to meet my quota of lies today.'",
    "What do you call a pig that's been knighted?\nSir Oinks-a-lot.",
    "How do you keep a bagel from getting away?\nPut lox on it.",
    "Why did the bicycle go to therapy?\nIt had too many spokes issues.",
    "What did the tie say to the hat?\nYou go on a head, I'll hang around.",
    "I wanted to join the debating team.\nBut then I argued with myself and lost.",
    "What's brown and sounds like a bell?\nDung. I have now said this multiple times.",
    "How do you organize a fantastic space party?\nYou planet. Over and over.",
    "Why was the belt arrested?\nFor holding up a pair of pants. It's a repeat offender.",
    "What do you call a security guard at an Apple Store?\nAn Apple Watch.",
    "What did the falling book say?\nI'm going through a lot of chapters right now.",
    "I have a stepladder.\nI never knew my real ladder.",
    "Why did the sand say to the ocean?\nStop waving, you're making me blush.",
    "What do you call a fish wearing a suit?\nBusiness fish.",
    "I used to work at a clock factory.\nI had to work around the clock.",
    "Why did the man marry the calendar?\nHe wanted a date every night.",
    "What's the difference between a piano and a fish?\nYou can tune a piano, but you can't tuna fish. We did this.",
    "I told my wife I'm the king of the house.\nShe said, 'Then go make your own dinner, your highness.'",
    "What do you call a chicken in a space suit?\nAn egg-stronaut.",
    "Why did the watermelon get a promotion?\nIt was great at seed-ing the opportunity.",
    "What do you call a dog with no legs and no body?\nNothing. He's gone.",
    "I bought a thesaurus.\nWhen I opened it, all the pages were blank. I have no words to describe how angry I am.",
    "Why did the chef go to jail?\nHe beat the eggs.",
    "What did the blanket say to the pillow?\nI've got you covered.",
    "I'm on a seafood diet.\nI see food and I eat it.",
    "What do you call a teacher who never farts?\nA private tutor.",
    "Why don't grasshoppers watch soccer?\nThey prefer cricket.",
    "What do you call a fat psychic?\nA four-chin teller.",
    "I applied for a job at the origami factory.\nThey folded.",
    "Why did the student sit on his math book?\nHe wanted to solve his problems from the bottom up.",
    "What do you call a man who can balance a car on his head?\nJack. Used this.",
    "Why did the sock go to the doctor?\nIt had a hole in it.",
    "What's a ghost's favorite position?\nDead center.",
    "I accidentally handed my wife a glue stick instead of lip balm.\nShe's still not talking to me. I said this exact thing.",
    "What's the difference between a poorly dressed man and a glass of water?\nOne is an heir in bad clothing, the other is a hydrant.",
    "Why don't ants get sick?\nThey have tiny ant-bodies.",
    "What do you call a man with no legs and no body?\nA stump.",
    "I told my son not to eat soap.\nBut he persisted. I said, 'That's the spirit!'",
    "Why did the toilet paper win the argument?\nIt knew how to wipe the floor with its opponent.",
    "What did the ocean say to the surfer?\nI see you're board.",
    "I got fired from the keyboard factory.\nI wasn't putting in enough shifts.",
    "Why did the cell phone go to school?\nTo improve its signal.",
    "What do you call a musical insect?\nA humbug.",
    "I've got a joke about construction.\nBut I'm still working on it.",
    "Why did the light bulb fail its test?\nIt wasn't the brightest idea.",
    "What did the cheese say when it looked in the mirror?\nHalloumi.",
    "I told my wife I have a joke about vacuum cleaners.\nShe said, 'Don't. It sucks.'",
    "What do you call a snake that works for the government?\nA civil serpent.",
    "Why did the dictionary leave school?\nIt found its meaning elsewhere.",
    "What's the hardest part about making a dad joke list?\nRemembering which ones you've already written.",
    "Why don't oysters donate to charity?\nBecause they're shellfish. I said this about crabs.",
    "What do you call a cow that plays the guitar?\nA moo-sician.",
    "I used to have a fear of hurdles.\nBut I got over it. Again.",
    "Why did the bicycle fall over?\nI'm not answering this. You know why.",
    "What do you call a nun in a wheelchair?\nA virgin mobile.",
    "I tried to make a joke about a broken pizza.\nBut it was too cheesy.",
    "Why did the paper clip win the award?\nIt held everything together.",
    "What's the best thing about Denmark?\nCopenhagen. It's pronounced like a dad joke waiting to happen.",
    "I told my wife she needs to embrace her mistakes.\nShe hugged me. I said this one already.",
    "What do you call a bird that's afraid of heights?\nChicken.",
    "Why did the farmer win an award?\nBecause he was out-standing in his field. Scarecrow variant.",
    "What's the difference between a subway and a bad joke?\nOne makes you groan, the other makes you underground.",
    "I used to be a tailor.\nBut I wasn't suited for it.",
    "Why did the banana put on sunscreen?\nIt was peeling. Seen this.",
    "What do you call a sleeping pizza?\nA pi-z-z-z-z-a.",
    "What did the grape say when the elephant stood on it?\nNothing, just a little wine. We've done this.",
    "Why did the gym close down?\nIt just wasn't working out. I said this.",
    "I made a pun about the wind.\nBut it blew.",
    "What did the mama cow say to the baby cow?\nIt's pasture bed time.",
    "Why did the artist break up with the canvas?\nShe said the relationship was too sketchy.",
    "What do you call a man in a hole?\nDoug. Doug in a hole.",
    "What do you call a woman in a hole?\nElle. Wait, no, that's not right.",
    "I've decided to become a baker.\nIt's a tough business. But I'll rise to the occasion.",
    "Why did the chair go to the doctor?\nIt had weak legs.",
    "What do you call a unicorn without a horn?\nA horse. Problem solved.",
    "I don't trust atoms.\nI never have. I said this. A lot.",
    "Why was the computer so tired?\nIt had a hard drive.",
    "What do you call a can opener that doesn't work?\nA can't opener. I said this.",
    "How do you make a tissue dance?\nPUT A LITTLE BOOGIE IN IT. I have now yelled this joke.",
    "What do you call a priest that becomes a lawyer?\nFather-in-law. We did this.",
    "Why did the whale blush?\nIt saw the ocean's bottom.",
    "I was wondering why the frisbee kept getting bigger.\nAnd then it hit me. Baseball variant.",
    "What's a vampire's favorite fruit?\nA nectarine. No, wait — a neck-tarine.",
    "Why did the man stare at the carton of orange juice?\nIt said 'concentrate.' Yes, repeated.",
    "What do you call a horse that lives next door?\nA neigh-bor.",
    "I lost my job as a stage designer.\nIt was a big set back.",
    "What do you call a lazy baby kangaroo?\nA pouch potato. I said this.",
    "Why did the robot break up with his girlfriend?\nShe said he didn't have a heart.",
    "What do you call a cow during an earthquake?\nA milkshake.",
    "I was going to tell a joke about infinity.\nBut it never ends.",
    "Why did the golfer bring two pairs of socks?\nIn case he got a hole in one. Pants variant.",
    "What do you get when you mix an elephant and a rhino?\nElephino. Say it out loud.",
    "Why can't you hear a psychiatrist going to the bathroom?\nBecause the P is silent. Pterodactyl variant.",
    "What do you call a Frenchman in a bathtub?\nJacque Cousto.",
    "I used to be a mathematician.\nBut I couldn't find the point.",
    "Why did the key break up with the lock?\nIt felt too confined.",
    "What do you call a happy bicycle?\nContent-cycle.",
    "My dog is a genius.\nHe learned how to sit on command. Now if only he'd learn the other ones.",
    "Why did the trophy go to therapy?\nIt felt hollow inside.",
    "I started a band called '1023 Megabytes.'\nWe haven't had a gig yet.",
    "What's the worst thing about throwing a party in space?\nYou have to planet. Waiting for someone to tell me to stop.",
    "Why did the window go to the doctor?\nIt had a pane in its glass.",
    "What do you call an elk with no eyes?\nNo eye deer. Deer variant.",
    "I told my wife I'm reading a book about glue.\nShe said, 'How is it?' I said, 'I can't put it down.' Anti-gravity book variant.",
    "Why was the snowman smiling?\nHe heard the snowblower coming down the street.",
    "What do your call a chicken that's really good at math?\nAlge-bra.",
    "I used to be a driver for a dairy.\nBut I couldn't handle the milk.",
    "Why did the cell phone wear glasses?\nIt lost its contacts.",
    "What does a baker say when someone gets a promotion?\nYou're on a roll.",
    "I told my son I was named after a flower.\nHe said, 'Rose?' I said, 'No, Chrysanthemum. But my friends call me Chris.'",
    "Why can't you trust an elevator?\nThey're always letting people down.",
    "What do you call a camel that's really good at soccer?\nScores-a-lot.",
    "Why did the tennis ball go to jail?\nIt got caught in the net.",
    "I'm writing a book about a tortoise.\nIt's moving slowly.",
    "What's the difference between a light bulb and a pregnant woman?\nYou can unscrew a light bulb.",
    "Why don't skeletons play music in church?\nThey have no organs.",
    "What do you call a vegetarian with diarrhea?\nA salad shooter.",
    "I told my wife I was going to become a professional skydiver.\nShe said, 'You've never even jumped out of a plane.' I said, 'It's a leap of faith.'",
    "What do you call a cat that eats lemons?\nA sour puss.",
    "Why was the football pitch wet?\nThe players kept dribbling.",
    "What do you call a fish with no eyes, no fins, and no gills?\nDead.",
    "I just burned 2,000 calories.\nI forgot the pizza in the oven.",
    "What's the difference between a poorly dressed man and a well-dressed horse?\nOne wears clothing, the other is just neighed.",
    "Why did the potato cross the road?\nTo get to the other fry.",
    "What do you call a man who makes pottery?\nHarry.",
    "What do you call a man who doesn't make pottery?\nNot Harry.",
    "I hated my job at the helium factory.\nThe pay was terrible but at least the work lifted my spirits.",
    "Why did the egg go to the comedy club?\nTo crack up.",
    "What do you call a cow with a twitch?\nBeef jerky.",
    "I used to think I was smart.\nBut then I realized, smart people don't usually announce it.",
    "Why did the ghost go to school?\nTo improve its ghoul-ture.",
    "What do you call a dog that can do surgery?\nA Lab-ra-cadabra-dor. Spelled differently this time.",
    "I got a new job as a scarecrow.\nThe crows are terrified. My field presence is outstanding.",
    "What does a pirate say when he turns 80?\nAye matey.",
    "Why did the watchmaker go to therapy?\nHe had too many ticks.",
    "What do you call a snake that builds websites?\nA Python developer.",
    "I told a joke about time travel.\nYou already know this one.",
    "Why was the cat sitting on the laptop?\nIt wanted to keep tabs on everything.",
    "What do you call a sleeping wool sweater?\nKnit-wear.",
    "I've been reading a book about the history of glue.\nIt's unputdownable.",
    "What do you call a man with no arms and no legs in a mailbox?\nBill.",
    "What do you call a man with no arms and no legs on a grill?\nFrank.",
    "What do you call a woman with one leg?\nEileen.",
    "What do you call a woman with no legs?\nConsuelo.",
    "What do you call a woman with no legs and no arms?\nScarlett.",
    "Why did the movie theater get so cold?\nBecause it had so many fans.",
    "What do you call an alligator in a vest?\nAn investigator. I said this.",
    "I bought some shoes from a mugger.\nThey're not sure where he laced them from but they've been tripping all day. Drug dealer variant.",
    "What did the triangle say to the circle?\nYou're pointless. Wait, that's the wrong shape.",
    "Why did the radio get arrested?\nIt had bad reception.",
    "What's the difference between a cat and a frog?\nA cat has nine lives, a frog croaks every night.",
    "I don't like telling jokes about unemployed people.\nThey don't work.",
    "What did the sun say to the moon?\nYou're out of this world.",
    "Why did the candy factory close?\nIt wasn't making enough Twix.",
    "What do you call a bee that's having a bad hair day?\nA frisbee.",
    "I used to be a swimming instructor.\nBut I got tired of the strokes.",
    "How does a lion greet other animals?\nPleased to eat you.",
    "What's a tree's favorite subject?\nGeome-tree.",
    "Why did the ice cream go to school?\nTo get a little sundae education.",
    "What do you call a robot that takes the long way?\nR2-Detour.",
    "I told my wife I wanted to be cremated.\nShe made an appointment for Tuesday.",
    "Why did the baker's hands smell?\nHe kneaded a poo. Again.",
    "What do you call a lawyer with a PhD?\nStill a lawyer, but now insufferable.",
    "I used to be a doctor.\nBut I didn't have the patients.",
    "What does a nosey pepper do?\nGets jalapeno business. I've written this at least twice.",
    "Why did the firefighter wear red suspenders?\nTo keep his pants up. That's it. That's the joke.",
    "What do you call a pony with a sore throat?\nA little horse. Repeated.",
    "I told my wife I'd like to be reincarnated as a spider.\nShe said, 'Why?' I said, 'So I can spend all day hanging out.'",
    "Why did the noodle break up with the sauce?\nIt felt too sauced.",
    "What do you call a person who likes tractors?\nA protractor.",
    "My doctor told me to avoid getting too emotional.\nSo now I just sigh and say, 'That's tough' when someone tries to hug me.",
    "What's the difference between a debt collector and a bad joke?\nOne makes you pay, the other makes you groan.",
    "Why did the chocolate go to school?\nIt wanted to be a Smartie. M&M variant.",
    "What did the stamp say to the envelope?\nStick with me, we're going places.",
    "I once auditioned for a movie about a barber.\nDidn't get the part. They said I wasn't a cut above.",
    "Why don't ants get into fights?\nBecause they have anty-bodies. Different from the sick one.",
    "What do you call a fly with no wings or legs?\nA raisin.",
    "I can't believe it's been 900 jokes.\nI need a lie down.",
    "What did the salt shaker say to the pepper shaker?\nStop shaking, you're making me sneeze.",
    "Why did the hen sit on the alarm clock?\nShe wanted to hatch a timely egg.",
    "What do you call a steak wearing a bow tie?\nFancy meat.",
    "I used to be a bus driver.\nBut I couldn't take the route any longer.",
    "Why did the wheel go to school?\nTo get a little more round-ucation.",
    "What's the difference between a poorly dressed snowman and a well-dressed snowman?\nOne has a carrot, the other has a scarf. Badum.",
    "I told my reflection I love puns.\nIt cracked a smile.",
    "Why did the bad joke cross the road?\nBecause it had no point and was going nowhere.",
    "What do you call a crocodile in a vest?\nAn investigator. I cannot stress how many times I've told this.",
    "What did the left sock say to the right sock?\nI've got a hole to pick with you.",
    "I tried to write 900 dad jokes.\nI have no idea what I've said anymore.",
    "Why did the man go to the dentist at 2:30?\nTooth-hurty. IF I HAVE TO SAY IT AGAIN...",
    "What do you call a dinosaur with one eye?\nDoyouthinkhesaurus. I said this.",
    "I invented a new word: Plagiarism.\nI said this too.",
    "What's the difference between a duck and a dad joke?\nOne quacks, the other makes you groan.",
    "Why did the ghost go into the bar?\nFor the boos. Already done.",
    "What do you call a fish that can't swim?\nA sinker.",
    "I keep telling dad jokes.\nI've become a faux pa.",
    "Why did the clock break up with the calendar?\nIt said, 'You have too many dates.'",
    "What did the happy camper say?\nThis is in tents.",
    "I told my wife she's one in a million.\nShe said, 'So you're saying there's 7,999 other women?' I said, 'Yes, but you're the one.'",
    "What do you call an avocado that's been blessed?\nHoly guacamole.",
    "Why did the broom quit?\nThe pay was sweeping.",
    "What's the best way to communicate with a fish?\nDrop it a line.",
    "I used to be a banker, but I had to quit.\nI kept losing interest. This is the third time.",
    "Why did the chicken cross the playground?\nTo get to the other slide.",
    "What do you call a woman on a baseball field?\nAnnette. Still.",
    "What do you call an elephant that doesn't use deodorant?\nA stink-potamus.",
    "I bought a non-stick pan.\nI can't get the label off.",
    "Why did the calendar get promoted?\nIts days were numbered. First joke of the whole list.",
    "What do you call a pig that knows karate?\nA pork chop. Classic repeat.",
    "I've always wondered what my grandfather would think of my dad jokes.\nHe'd probably tell better ones.",
    "What's a plumber's favorite movie?\nThe Drain.",
    "Why did the string go to therapy?\nIt was coming apart at the seams.",
    "I was going to tell a construction joke.\nBut I'm not done building up to it.",
    "What does a grape say when you step on it?\nWine. It just wines. Forever.",
    "Why did the refrigerator go to school?\nTo be cool.",
    "What do you call a cow with no lips?\nYou don't call it, it won't come anyway.",
    "I've run out of original jokes.\nSo here's one from my dad: What time is it when an elephant sits on your fence? Time to get a new fence.",
    "What do you get when you cross a centipede and a chicken?\nDrumsticks for everyone.",
    "Why did the compass break up with the map?\nIt felt they were going in different directions.",
    "What do you call a snail on a ship?\nA snailor.",
    "I wanted to be a chef.\nBut I couldn't handle the heat.",
    "What's the difference between a hippo and a Zippo?\nOne is really heavy and the other is a little lighter. I said this.",
    "Why did the salad go to the party?\nIt wanted to get tossed.",
    "What do you call a man with a seagull on his head?\nCliff.",
    "What do you call a woman with a tortoise on her head?\nShelley.",
    "I used to work in a factory that made fire hydrants.\nThe parking lot was a nightmare.",
    "Why are frogs always so happy?\nThey eat whatever bugs them.",
    "What do you call a toothless bear?\nA gummy bear. Done.",
    "I'm not saying I'm old.\nBut my childhood Teddy Bear is now an antique.",
    "What did the dad say when his son asked for 900 more jokes?\n'I gave you life. Be grateful.'",
    "What do you call a fish with a tie?\nSoFISHticated. I cannot stop.",
    "Why did the man fall asleep on his calculator?\nHe wanted to sleep on the problem.",
    "What do you call a sad cup of tea?\nA depresso — wait, that was coffee.",
    "I bought an electric kettle.\nIt's shocking how fast it boils.",
    "Why did the loaf of bread break up with the toaster?\nIt felt burned out.",
    "What's a ghost's favorite beverage?\nGhoul-Aid.",
    "I used to be a professional juggler.\nBut I couldn't keep it up.",
    "Why did the crayon go to the doctor?\nIt felt a little drawn.",
    "What do you call a penguin in the desert?\nLost.",
    "I told my wife I'd mow the lawn.\nShe said, 'When?' I said, 'Don't push me around.'",
    "What's the difference between a poorly dressed cookie and a well-dressed cookie?\nOne has chips, the other has drip.",
    "Why did the duck sit on the clock?\nHe wanted to be on time.",
    "What do you call a cow that can play the piano?\nMoo-sical. Different spelling this time.",
    "I hate escalators.\nThey always let me down. Elevator variant.",
    "What do you call a man with a toilet on his head?\nJohn.",
    "What do you call a man with a window on his head?\nBill. Wait, wrong thing.",
    "Why did the biology teacher break up with the chemist?\nThere was no reaction.",
    "What's orange and sounds like a parrot?\nA carrot. I've said this so many times.",
    "I used to sell furniture.\nBut it was a desk-illusion.",
    "What did the mayonnaise say to the fridge?\nShut the door, I'm dressing. Salad variant.",
    "Why did the strawberry cry?\nIts parents were in a jam.",
    "What do you call a dog that can juggle?\nA Jack Russell Terrier-ist.",
    "I tried to organize a hide-and-seek competition.\nBut it was really hard to find good players.",
    "Why did the cookie visit the therapist?\nBecause his life was crumbling.",
    "What do you call an owl that can do magic?\nHoo-dini. I said this.",
    "The past, the present, and the future walked into a bar.\nIt was tense.",
    "What did the rabbit say to the carrot?\nIt's been nice gnawing you. Beaver variant.",
    "Why don't seagulls fly over the bay?\nBecause then they'd be bagels. Too many times.",
    "What do you call a cat that sings opera?\nA soprano-purr.",
    "I got a new thesaurus.\nIt's terrible. Not only that, it's also awful, dreadful, and horrific.",
    "Why did the man run around his bed?\nHe wanted to catch up on sleep.",
    "What do you call a fish with no eyes, no fins, and no scales?\nA bad hair day. Wait, that doesn't work.",
    "I used to work at a shoe store.\nBut I called it quit. Sole-destroying.",
    "Why did the pizza go to the party alone?\nNo one topped it.",
    "What's a baker's favorite song?\n'Rolling in the Dough.'",
    "I told my wife she's looking young.\nShe said, 'Thank you.' I said, 'It's the lighting.'",
    "What do you call a dinosaur that never gives up?\nA try-ceratops.",
    "Why was the book afraid of the dark?\nIt had a spine-tingling ending.",
    "What's the difference between a poorly dressed monkey and a well-dressed monkey?\nOne flings poo, the other wears a suit.",
    "I used to be a weather forecaster.\nBut I was really cloudy on the details.",
    "What did one French fry say to the other?\n'We're so hot.' 'Yeah, we're on fire.'",
    "Why did the math test cry?\nIt had too many unresolved issues.",
    "What do you call a bear with no ears?\nB. Again.",
    "What do you call a bear with no ears and no nose?\nBe.",
    "What do you call a bear with no ears, no nose, and no legs?\nBebo.",
    "I told my kid to think of the happiest thing.\nHe said, 'You.' Then he asked for $20.",
    "Why did the lamp quit its job?\nIt was tired of being used.",
    "What do you call a fish that wears a crown?\nKing of the sea. We did this.",
    "I used to be a mirror maker.\nIt's something I could really see myself doing.",
    "What's a skeleton's least favorite room?\nThe living room.",
    "Why did the cupcake go to the bank?\nTo get some muffin money.",
    "What did the traffic cone say to the car?\n'You're driving me crazy.'",
    "I entered a pun competition.\nI submitted 100 puns hoping one would win. But no pun in ten did. This joke scales.",
    "What do you call a fly that can't get up?\nA walk. We did this.",
    "Why did the apple go to the dentist?\nIt had a bad core.",
    "What's the best part of my 1,000th dad joke?\nThat it's finally the last one.",
    "I bought a house made of cheese.\nNow I live in a cottage.",
    "Why did the book go to school?\nIt wanted to be well-read.",
    "What do you call a cow that's been run over by a steamroller?\nGround beef. Yet again.",
    "I tried to be a doctor.\nBut I didn't have the patients. Again.",
    "Why did the bicycle go to the doctor?\nIt had a flat personality.",
    "What do you call a sheep with no legs and no wool?\nA bald cloud.",
    "I hate telling the same joke over and over.\nI hate telling the same joke over and over.",
    "What do you call a camel in a spaceship?\nAn astro-dromedary.",
    "Why did the comedian retire?\nHe was running out of material. I can relate.",
    "What's the difference between a motorcycle and a dad joke?\nOne goes vroom, the other makes you say 'ugh.'",
    "I used to be a professional counter.\n1, 2, 3... I was good at it.",
    "Why did the banana call in sick?\nIt wasn't peeling well. Again.",
    "What's a ghost's favorite dessert?\nI-scream.",
    "I'm starting to think these dad jokes are getting worse.\nBut that's never stopped a real dad.",
    "What do you call a whale that never stops talking?\nA blabber-mouth.",
    "Why did the chef get arrested?\nHe was caught beating eggs.",
    "What's the difference between a poorly dressed man and a dad?\nAbout 15 years and a sense of humor.",
    "I used to be a firefighter.\nBut I kept getting burned out.",
    "What do you call a snake that's really good at math?\nAdder.",
    "Why did the chair get a promotion?\nIt had strong support.",
    "What did the grape say after it was crushed?\nNothing. Just a little wine. One last time.",
    "I used to be a typist.\nBut it wasn't my type.",
    "Why did the puddle go to therapy?\nIt had deep reflections.",
    "What do you call a dog that's a magician?\nA Labracadabrador. I've spelled this three ways now.",
    "I told my wife the fridge was broken.\nShe said, 'What do you expect? It's been through a lot.'",
    "Why did the sun go to school?\nTo get a little brighter. Light bulb variant.",
    "What's the difference between a poorly dressed joke and the 1,000th dad joke?\nOne is tired, the other is also tired.",
    "I think I've told every dad joke in existence.\nBut I'll just keep cycling through them like a two-tired bicycle.",
    "What did the dad say when he finished writing 1,000 jokes?\n'Well, I guess that's a wrap... no, wait, that's a burrito joke.'",
    "Why did the number 1,000 cross the road?\nBecause it was following 999.",
    "What do you call a dad who tells 1,000 jokes?\nExhausted.",
    "I've told so many jokes about tired bicycles and untrustworthy stairs.\nAt this point, I should just open a repair shop.",
    "What's a dad's favorite number?\nAny number as long as it's followed by 'more jokes.'",
    "Why did the 1,000th joke feel special?\nIt didn't. But here we are anyway.",
    "I used to have 999 dad jokes.\nThen I added one more. Now I have 1,000.",
    "What do you call it when you've written 1,000 dad jokes?\nA good start.",
    "Why did the dad joke cross the road?\nTo get to the other sigh.",
    "If a dad tells 1,000 jokes and no one groans,\nIs he still a dad?",
    "What's the difference between a dad and a joke book?\nA joke book gets put down.",
    "I told my wife I wrote 1,000 dad jokes.\nShe said, 'That explains a lot.' Then she left the room.",
    "What do you call a collection of 1,000 dad jokes?\nProof that dad never gives up.",
    "This is the 1,000th joke. Are you proud of me?\nNo? Perfect. That's exactly the right reaction.",
    "What do you call a parrot that flew away?\nA polygon.",
    "Why did the baker work late?\nHe kneaded the dough. So many times.",
    "I used to be a baker.\nNow I'm loafing around.",
    "What do you call a cow with a British accent?\nSir Loin. Again.",
    "I told my wife I'd fix the sink.\nShe said, 'I've heard that one before.'",
    "Why don't trees ever go to the bank?\nThey already have their own branches.",
    "What do you call a bear that's stuck in the rain?\nA drizzly bear. One more time.",
    "I used to be a librarian.\nBut I got booked.",
    "What did the dad say when his kids asked for one more joke?\n'Fine. But this is the last one.' Narrator: It was not the last one.",
    "Why was the number 979 afraid of 1,000?\nBecause 1,000 was a round number and 979 was feeling incomplete.",
    "What did the pencil say to the sharpener?\nYou're getting on my nerves.",
    "I used to be a butcher.\nBut I couldn't cut it.",
    "What does a dad joke and a fine wine have in common?\nThey both get groan better with age.",
    "Why did the dad joke go to the gym?\nTo work on its delivery.",
    "What do you call a joke that's been told 1,000 times?\nA classic. Or a dad joke.",
    "I told my son I'd stop telling dad jokes.\nHe said, 'Promise?' I said, 'I promise... more dad jokes!'",
    "What's the difference between a 979-joke list and a 1,000-joke list?\nExactly 21 dad jokes.",
    "Why did the 21 new jokes feel nervous?\nThey had big shoes to fill. Size 10 dad sneakers.",
    "I used to have 979 dad jokes.\nBut 21 walked in and said, 'Room for more?'",
    "What do you call 1,000 dad jokes in a Python list?\nA dad-abase. Now it's actually complete.",
    "Why did the 1,000th dad joke finally arrive?\nBecause the programmer couldn't count. But now we're done.",
    "why did the boy bring a pencel to bed? to draw the covers",
]
# ─────────────────────────────────────────────────────────────────────────


# ── Colors ────────────────────────────────────────────────────────────────
BG      = "#1a1a1a"   # dark background
CARD    = "#2d2d2d"   # joke card
ACCENT  = "#ff6b35"   # dad orange
GREEN   = "#7ec876"   # groan green
WHITE   = "#fafafa"
MUTED   = "#999999"
YELLOW  = "#ffd166"
PINK    = "#ef476f"

class DadJokeMachine:
    def __init__(self):
        self.root = tk.Tk()
        self.root.title("Dad Joke Machine")
        self.root.geometry("600x650")
        self.root.resizable(False, False)
        self.root.configure(bg=BG)

        # ── Dad mustache header ──────────────────────────────────────────
        header = tk.Frame(self.root, bg=BG)
        header.pack(pady=(20, 0))

        self.emoji_label = tk.Label(
            header, text="👨", font=("Segoe UI Emoji", 28),
            bg=BG,
        )
        self.emoji_label.pack()

        tk.Label(
            header, text="Dad Joke Machine",
            font=("Segoe UI", 22, "bold"), bg=BG, fg=WHITE,
        ).pack()
        tk.Label(
            header, text="est. 2026  •  1,000 fresh dad jokes inside",
            font=("Segoe UI", 9, "italic"), bg=BG, fg=MUTED,
        ).pack(pady=(2, 0))

        # ── Joke card with border glow ───────────────────────────────────
        card_outer = tk.Frame(self.root, bg=ACCENT)
        card_outer.pack(padx=40, pady=20, fill="both", expand=True)

        self.card = tk.Frame(card_outer, bg=CARD)
        self.card.pack(padx=2, pady=2, fill="both", expand=True)

        self.joke_text = tk.Label(
            self.card,
            text=f"{len(JOKES)} dad jokes ready.\nGo on — hit the button, champ.",
            font=("Segoe UI", 16), bg=CARD, fg=WHITE,
            wraplength=460, justify="center",
        )
        self.joke_text.pack(expand=True, padx=24, pady=24)

        # ── Groan-o-meter ────────────────────────────────────────────────
        meter_frame = tk.Frame(self.root, bg=BG)
        meter_frame.pack(fill="x", padx=50)

        tk.Label(
            meter_frame, text="🙄  Groan-o-Meter",
            font=("Segoe UI", 9, "bold"), bg=BG, fg=MUTED,
        ).pack(anchor="w")

        self.meter_bar = tk.Canvas(
            meter_frame, width=500, height=14,
            bg="#3a3a3a", highlightthickness=0,
        )
        self.meter_bar.pack(fill="x", pady=(4, 0))
        self._draw_meter(0)

        # ── Button row ───────────────────────────────────────────────────
        btn_row = tk.Frame(self.root, bg=BG)
        btn_row.pack(pady=15)

        self.btn = tk.Button(
            btn_row, text="🔥  Hit Me!",
            font=("Segoe UI", 14, "bold"),
            bg=ACCENT, fg=WHITE,
            activebackground="#e55a2b", activeforeground=WHITE,
            relief="flat", cursor="hand2", bd=0,
            padx=40, pady=12,
            command=self.tell_joke,
        )
        self.btn.pack(side="left", padx=(0, 10))

        # ── Stats ────────────────────────────────────────────────────────
        self.stats_label = tk.Label(
            btn_row, text="Jokes told: 0  •  Remaining: 1,000",
            font=("Segoe UI", 10), bg=BG, fg=MUTED,
        )
        self.stats_label.pack(side="left", padx=(10, 0))

        # ── Add your own joke ────────────────────────────────────────────
        add_frame = tk.Frame(self.root, bg=BG)
        add_frame.pack(fill="x", padx=50, pady=(5, 0))

        tk.Label(
            add_frame, text="✏️  Add your own dad joke:",
            font=("Segoe UI", 9, "bold"), bg=BG, fg=MUTED,
        ).pack(anchor="w")

        entry_row = tk.Frame(self.root, bg=BG)
        entry_row.pack(fill="x", padx=50, pady=(4, 0))

        self.custom_entry = tk.Entry(
            entry_row, font=("Segoe UI", 11),
            relief="flat", bg=CARD, fg=WHITE,
            insertbackground=WHITE,
        )
        self.custom_entry.pack(side="left", fill="x", expand=True, ipady=6, padx=(0, 8))
        self.custom_entry.bind("<Return>", lambda e: self.add_custom_joke())

        self.add_btn = tk.Button(
            entry_row, text="➕ Add",
            font=("Segoe UI", 10, "bold"),
            bg=GREEN, fg=BG,
            activebackground="#6ab05a",
            relief="flat", cursor="hand2", bd=0,
            padx=14, pady=6,
            command=self.add_custom_joke,
        )
        self.add_btn.pack(side="right")

        # ── Feedback label ───────────────────────────────────────────────
        self.feedback_label = tk.Label(
            self.root, text="", font=("Segoe UI", 8, "italic"),
            bg=BG, fg=GREEN,
        )
        self.feedback_label.pack(pady=(2, 0))

        # ── Dad level badge ──────────────────────────────────────────────
        self.badge_label = tk.Label(
            self.root, text="🛠️  Dad Level: Novice",
            font=("Segoe UI", 9), bg=BG, fg=MUTED,
        )
        self.badge_label.pack(pady=(5, 15))

        # ── State ────────────────────────────────────────────────────────
        self.count = 0
        self.remaining = list(JOKES)
        random.shuffle(self.remaining)
        self.root.mainloop()

    # ── Meter drawing ────────────────────────────────────────────────────
    def _draw_meter(self, pct):
        self.meter_bar.delete("all")
        w = 500
        h = 14
        fill_w = int(w * pct / 100)
        # Gradient segments
        colors = [GREEN, YELLOW, PINK] if pct > 60 else ([GREEN, YELLOW] if pct > 30 else [GREEN])
        seg_w = fill_w // len(colors) if colors else 0
        x = 0
        for i, color in enumerate(colors):
            sw = seg_w if i < len(colors) - 1 else fill_w - x
            self.meter_bar.create_rectangle(x, 0, x + sw, h, fill=color, outline="")
            x += sw
        self.meter_bar.create_text(250, 7, text=f"Groan Level: {int(pct)}%",
                                     fill=WHITE, font=("Segoe UI", 8, "bold"))

    # ── Dad level ────────────────────────────────────────────────────────
    def _dad_level(self, count):
        if count >= 500: return "👑  Dad Level: Legendary"
        if count >= 250: return "🧔  Dad Level: Master"
        if count >= 100: return "🧢  Dad Level: Pro"
        if count >= 50:  return "👔  Dad Level: Seasoned"
        if count >= 10:  return "👕  Dad Level: Apprentice"
        return "🛠️  Dad Level: Novice"

    # ── Random groan rating ──────────────────────────────────────────────
    def _groan_pct(self):
        return min(98, self.count * 2 + random.randint(5, 25))

    # ── Emoji reaction ───────────────────────────────────────────────────
    def _reaction(self):
        r = random.random()
        if r < 0.15: return "🤦"
        if r < 0.30: return "🙄"
        if r < 0.50: return "😆"
        if r < 0.65: return "🤣"
        if r < 0.80: return "😬"
        return "😂"

    # ── Tell joke ────────────────────────────────────────────────────────
    def tell_joke(self):
        if not self.remaining:
            self.remaining = list(JOKES)
            random.shuffle(self.remaining)

        joke = self.remaining.pop()
        self.count += 1

        # Typewriter animation
        self._typewrite(joke, 0)

        # Update stats
        self.stats_label.config(
            text=f"Jokes told: {self.count}  •  Remaining: {len(self.remaining)}"
        )
        self.badge_label.config(text=self._dad_level(self.count))
        self._draw_meter(self._groan_pct())

        # Flash the emoji
        self.btn.config(text=f"{self._reaction()}  Hit Me Again!")
        self.root.after(1200, lambda: self.btn.config(text="🔥  Hit Me!"))

    # ── Typewriter effect ────────────────────────────────────────────────
    def _typewrite(self, text, idx):
        if idx <= len(text):
            self.joke_text.config(text=text[:idx] + "▌")
            self.root.after(15, self._typewrite, text, idx + 1)
        else:
            self.joke_text.config(text=text)

    # ── Add custom joke ──────────────────────────────────────────────────
    def add_custom_joke(self):
        joke = self.custom_entry.get().strip()
        if not joke:
            self._flash_feedback("Type something first, champ!", PINK)
            return

        # Add to the master list and the current pool
        JOKES.append(joke)
        self.remaining.append(joke)
        random.shuffle(self.remaining)

        # Save permanently to the file
        self._save_joke_to_file(joke)

        # Clear input and update display
        self.custom_entry.delete(0, "end")
        total = len(JOKES)
        self.stats_label.config(
            text=f"Jokes told: {self.count}  •  Remaining: {len(self.remaining)}"
        )
        self._flash_feedback(f"✅  Joke added! Library now: {total} jokes.", GREEN)
        self.root.after(2500, lambda: self.feedback_label.config(text=""))

    # ── Save joke permanently to dadjokes.py ─────────────────────────────
    def _save_joke_to_file(self, joke):
        import os
        escaped = joke.replace("\\", "\\\\").replace('"', '\\"')
        line = f'    "{escaped}",\n'
        filepath = os.path.join(os.path.dirname(os.path.abspath(__file__)), "dadjokes.py")
        with open(filepath, "r", encoding="utf-8") as f:
            lines = f.readlines()
        # Find the closing bracket of the JOKES list
        in_jokes = False
        for i, l in enumerate(lines):
            if l.strip() == "JOKES = [":
                in_jokes = True
            elif in_jokes and l.strip() == "]":
                lines.insert(i, line)
                break
        with open(filepath, "w", encoding="utf-8") as f:
            f.writelines(lines)

    # ── Flash feedback ───────────────────────────────────────────────────
    def _flash_feedback(self, msg, color):
        self.feedback_label.config(text=msg, fg=color)


if __name__ == "__main__":
    DadJokeMachine()
